config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      sessions: 'users/sessions',
      registrations: "signup",
      omniauth_callbacks: 'users/omniauth_callbacks'
    }
  devise_scope :user do
    get 'registration_index', to: 'signup#index'
    get 'registration_nickname', to: 'signup#registration_nickname'
    get 'registration_sms', to: 'signup#registration_sms'
    get 'registration_address', to: 'signup#registration_address'
    get 'registration_card', to: 'signup#registration_card'
    get 'registration_done', to: 'signup#registration_done'
  end


  root "products#index"
  resources :products do
    member do
      get 'purchase'
      get 'purchase_done'
      get 'buy', to: 'products#buy'
      get 'done', to: 'products#done'
    end
  end
    
  # resources :signup do
  #   collection do
  #     get 'registration_nickname'
  #     get 'registration_sms'
  #     get 'registration_address'
  #     get 'registration_card'
  #     get 'registration_done'
  #   end
  # end

  resources :mypages do
    collection do
      get 'credit'
      get 'exhibition'
      get 'identification'
      get 'logout'
      get 'profile'
    end
  end

  resources :cards do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

  resources :purchases do
    member do
      post 'pay', to: 'purchases#pay'
    end
  end

end

app/models/signup.rb
class Signup < ApplicationRecord
end

app/controllers/signup_controller.rb
# class SignupController < ApplicationController
class SignupController < Devise::RegistrationsController
  before_action :validates_registration_nickname, only: :registration_sms # step1のバリデーション
  before_action :validates_registration_sms, only: :registration_address # registration_addressのバリデーション
  before_action :validates_registration_address, only: :create # step3のバリデーション

  def index
    session[:id] = nil
    session[:nickname] = nil
    session[:email] = nil
    session[:password] = nil
    session[:password_confirmation] = nil
    session[:birthday_year] = nil
    session[:birthday_month] = nil
    session[:birthday_day] = nil
    session[:phonennumber] = nil
  end

  def registration_nickname
    @user = User.new # 新規インスタンス作成
  end

  def registration_sms
    @user = User.new # 新規インスタンス作成
  end

  def registration_address
    @user = User.new # 新規インスタンス作成
    @user.build_address
  end

  def create
    @user.save!
    session[:id] = @user.id
    session[:nickname] = nil
    session[:email] = nil
    session[:password] = nil
    session[:password_confirmation] = nil
    session[:birthday_year] = nil
    session[:birthday_month] = nil
    session[:birthday_day] = nil
    session[:phonennumber] = nil
    redirect_to registration_card_path
  end

  def registration_card
  end

  def registration_done
    sign_in User.find(session[:id]) unless user_signed_in?
    session[:id] = nil
  end


  private

  def user_params
    params.require(:user).permit(
      :nickname, 
      :email, 
      :password, 
      :password_confirmation,
      :family_name, 
      :first_name, 
      :j_family_name, 
      :j_first_name, 
      :birthday_year, 
      :birthday_month, 
      :birthday_day, 
      :phonennumber,
      address_attributes: [:postal_code, :prefectuer, :city_ward, :address, :building,:tel,:id]
  )
  end

  def validates_registration_nickname
    # step1で入力した値をsessionに保存
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:birthday_year] = user_params[:birthday_year]
    session[:birthday_month] = user_params[:birthday_month]
    session[:birthday_day] = user_params[:birthday_day]
    @user = User.new(
      nickname: session[:nickname], # sessionに保存された値をインスタンスに渡す
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      birthday_year: session[:birthday_year], 
      birthday_month: session[:birthday_month], 
      birthday_day: session[:birthday_day],
      phonennumber: 12345678901,
      family_name: "あ",
      first_name: "い",
      j_family_name: "ア",
      j_first_name: "イ",
    )
    render :registration_nickname unless @user.valid?
  end


  def validates_registration_sms
    # step2で入力した値をsessionに保存
    session[:phonennumber] = user_params[:phonennumber]
    @user = User.new(
      nickname: session[:nickname], # sessionに保存された値をインスタンスに渡す
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      birthday_year: session[:birthday_year], 
      birthday_month: session[:birthday_month], 
      birthday_day: session[:birthday_day],
      phonennumber: session[:phonennumber],
      family_name: "あ",
      first_name: "い",
      j_family_name: "ア",
      j_first_name: "イ",
    )
    render :registration_sms unless @user.valid?
  end


  def validates_registration_address
    @user = User.new(user_params)
    @user.nickname = session[:nickname]
    @user.email = session[:email]
    @user.password = session[:password]
    @user.password_confirmation = session[:password_confirmation]
    @user.birthday_year = session[:birthday_year]
    @user.birthday_month = session[:birthday_month]
    @user.birthday_day = session[:birthday_day]
    @user.phonennumber = session[:phonennumber]
    render :registration_address unless @user.valid?
  end
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signup/data2.html.haml
.content
  .second__stage__header
    .logo-box
      .logo-box__logo
        =link_to root_path do
          = image_tag "fmarket_logo_red.svg", size: "185x49", alt: "フリマのアイコン"
      .logo-box__logo2
        .logo-box__logo2__text
          .logo-box__logo2__text__text1
            会員情報
          .logo-box__logo2__text__text2
            電話番号承認
          .logo-box__logo2__text__text3
            お届け先住所入力
          .logo-box__logo2__text__text4
            支払い方法
          .logo-box__logo2__text__text5
            完了
        .logo-box__logo2__point
          .logo-box__logo2__point__point1
          .logo-box__logo2__point__point2
          .logo-box__logo2__point__point3
          .logo-box__logo2__point__point4
          .logo-box__logo2__point__point5
          .logo-box__logo2__point__bar1
          .logo-box__logo2__point__bar2
          .logo-box__logo2__point__bar3
          .logo-box__logo2__point__bar4
  .center
    .center__content
      .top
        %h2電話番号の確認
      .main
        .main__text
          .main__text__top
            %h2携帯電話の番号
            .main__text__top__box
          %p本人確認のため、携帯電話のSMS(ショートメッセージービス)を利用して認証を行います。
        = link_to "http://localhost:3000/signup/data3" do
          .main__text__btn
            %h3 SMSを送信する
          %p※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
          .main__text__bottom
            = link_to ('http://localhost:3000/signup/registration_data3'), class: "info" do
              電話番号の確認が必要な理由
              = icon("fas", "chevron-right",class: "arrow")
              %span<>  
  .footer
    .footer_center
      プライバシーポリシー メルカリ利用規約 特定商取引
      .gray
        =link_to root_path do
          = image_tag "logo_gray.svg", size: "80x65", alt: "フリマのアイコン"
      .inc © Mercari, Inc.

app/views/signup/data4.html.haml
.content
  .fourth__stage__header
    .logo-box
      .logo-box__logo
        =link_to root_path do
          = image_tag "fmarket_logo_red.svg", size: "185x49", alt: "フリマのアイコン"
      .logo-box__logo2
        .logo-box__logo2__text
          .logo-box__logo2__text__text1
            会員情報
          .logo-box__logo2__text__text2
            電話番号承認
          .logo-box__logo2__text__text3
            お届け先住所入力
          .logo-box__logo2__text__text4
            支払い方法
          .logo-box__logo2__text__text5
            完了
        .logo-box__logo2__point
          .logo-box__logo2__point__point1
          .logo-box__logo2__point__point2
          .logo-box__logo2__point__point3
          .logo-box__logo2__point__point4
          .logo-box__logo2__point__point5
          .logo-box__logo2__point__bar1
          .logo-box__logo2__point__bar2
          .logo-box__logo2__point__bar3
          .logo-box__logo2__point__bar4
  .payment_main
    .center_box
      .regist-title
        支払い方法
      .card_number
        .box
          .box_in
            %label{for: "name"} カード番号
            %span.form-require 必須
            .form
            .icons
              = image_tag "cards.png", size: "343x49", alt: "カードのアイコン"
      .expiration_date
        %label{for: "name"} 有効期限
        %span.form-require 必須
        .expiration_day_year
          .year
          %h2年
        .expiration_day_month
          .month
          %h2月
        .security_code
          .in_box
            .in_block
              %label{for: "name"} セキュリティーコード
              %span.form-require 必須
              .code_box
              %h3カード裏面の番号とは
              %h3.blue__question?
      = link_to "http://localhost:3000/signup/data5" do
        .next_btn
          %button.u-box.btn-red{type: "submit"} 次へ進む  
  .footer      
    .footer_center
      プライバシーポリシー メルカリ利用規約 特定商取引
      .gray
        =link_to root_path do
          = image_tag "logo_gray.svg", size: "80x65", alt: "フリマのアイコン"
      .inc © Mercari, Inc.

app/views/signup/data5.html.haml
.content
  .five_stage_header
    .logo-box
      .logo-box__logo
        =link_to root_path do
          = image_tag "fmarket_logo_red.svg", size: "185x49", alt: "フリマのアイコン"
      .logo-box__logo2
        .logo-box__logo2__text
          .logo-box__logo2__text__text1
            会員情報
          .logo-box__logo2__text__text2
            電話番号承認
          .logo-box__logo2__text__text3
            お届け先住所入力
          .logo-box__logo2__text__text4
            支払い方法
          .logo-box__logo2__text__text5
            完了
        .logo-box__logo2__point
          .logo-box__logo2__point__point1
          .logo-box__logo2__point__point2
          .logo-box__logo2__point__point3
          .logo-box__logo2__point__point4
          .logo-box__logo2__point__point5
          .logo-box__logo2__point__bar1
          .logo-box__logo2__point__bar2
          .logo-box__logo2__point__bar3
          .logo-box__logo2__point__bar4
  .regist_main
    .center_box
      .done-title
        会員登録完了
      .done__message
        .h1
          %h1ありがとうございます。
          %h1会員登録が完了しました。
        .next_btn
        = link_to 'http://localhost:3000/' do
          %button.u-box.btn-red{type: "submit"} メルカリをはじめる
        .image
          = link_to 'http://localhost:3000/signup/index' do
            = image_tag "startfmarket.png", size: "420x420", alt: "フリマスタート"
  .footer      
    .footer_center
      プライバシーポリシー メルカリ利用規約 特定商取引
      .gray
        =link_to root_path do
          = image_tag "logo_gray.svg", size: "80x65", alt: "フリマのアイコン"
      .inc © Mercari, Inc.

app/views/signup/ragistration_data1.html.haml
.content
  .first__stage__header
    .logo-box
      .logo
        =link_to root_path do
          = image_tag "fmarket_logo_red.svg", size: "185x49", alt: "フリマのアイコン"
      .first-phase
        = image_tag "step1.png", size: "557x130", alt: "第一段階"
  .regstration__data__box
    .center-box
      .regist-title 会員情報入力
      .frame
        .inframe
          .white-square
            .form-block
              %label{for: "name"} ニックネーム
              %span.form-require 必須
              .white_box
          .white-square
            .form-block
              %label{for: "name"} メールアドレス
              %span.form-require 必須
              .white_box
          .white-square
            .form-block
              %label.name パスワード
              %span.form-require 必須
              .white_box
          .text-gray※ 英字と数字の両方を含めて設定してください
          .word-box
          %input#sample_checkbox{type: "checkbox"}/
          %label.name パスワードを表示する
          .identification
            .i-text
              安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
          %label{for: "name"} お名前（全角）
          %span.form-require 必須
          .name_kanji_box
            .name_last
            .name_first
          %label{for: "name"} お名前（カナ）
          %span.form-require 必須
          .name_kana_box
            .name_kana_last
            .name_kana_first
          %label{for: "name"} 生年月日
          %span.form-require 必須
          .birthday
            .year
            <span>年</span>
            .month
            <span>月</span>
            .day
            <span>日</span>
            .identification   
          .text-gray※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
          .u-text「次へ進む」のボタンを押すことにより、<a href="http://localhost:3000/signup/registration_data2_blank">利用規約</a>に同意したものとみなします
          = link_to 'http://localhost:3000/signup/registration_data2' do
            %button.u-box.btn-red{type: "submit"} 次へ進む
            .text-blue 本人情報の登録について>
            %p.under-text
              This site is protected by reCAPTCHA and the Google <a href="https://policies.google.com/privacy" target="_blank">Privacy Policy</a> and <a href="https://policies.google.com/terms" target="_blank">Terms of Service</a> apply.
  %i.icon-arrow-right       
  .footer
    .footer_center
      プライバシーポリシー メルカリ利用規約 特定商取引
      .gray
        =link_to root_path do
          = image_tag "logo_gray.svg", size: "80x65", alt: "フリマのアイコン"
      .inc © Mercari, Inc.

app/views/signup/ragistration_data2.html.haml
.content
  .second__stage__header
    .logo-box
      .logo
        =link_to root_path do
          = image_tag "fmarket_logo_red.svg", size: "185x49", alt: "フリマのアイコン"
      .first-phase
        = image_tag "step-2.png", size: "590x130", alt: "第二段階"
  .center
    .center__content
      .top
        %h2電話番号の確認
      .main
        .main__text
          .main__text__top
            %h2携帯電話の番号
            .main__text__top__box
          %p本人確認のため、携帯電話のSMS(ショートメッセージービス)を利用して認証を行います。
        = link_to 'http://localhost:3000/signup/registration_data3' do
          .main__text__btn
            %h3 SMSを送信する
          %p※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
          .main__text__bottom
            = link_to ('http://localhost:3000/signup/registration_data3'), class: "info" do
              電話番号の確認が必要な理由
              = icon("fas", "chevron-right",class: "arrow")
              %span<>  
  .footer
    .footer_center
      プライバシーポリシー メルカリ利用規約 特定商取引
      .gray
        =link_to root_path do
          = image_tag "logo_gray.svg", size: "80x65", alt: "フリマのアイコン"
      .inc © Mercari, Inc.

app/views/signup/ragistration_data4.html.haml
.content
  .fourth__stage__header
    .logo-box
      .logo-box__logo
        =link_to root_path do
          = image_tag "fmarket_logo_red.svg", size: "185x49", alt: "フリマのアイコン"
      .logo-box__logo2
        .logo-box__logo2__text
          .logo-box__logo2__text__text1
            会員情報
          .logo-box__logo2__text__text2
            電話番号承認
          .logo-box__logo2__text__text3
            お届け先住所入力
          .logo-box__logo2__text__text4
            支払い方法
          .logo-box__logo2__text__text5
            完了
        .logo-box__logo2__point
          .logo-box__logo2__point__point1
          .logo-box__logo2__point__point2
          .logo-box__logo2__point__point3
          .logo-box__logo2__point__point4
          .logo-box__logo2__point__point5
          .logo-box__logo2__point__bar1
          .logo-box__logo2__point__bar2
          .logo-box__logo2__point__bar3
          .logo-box__logo2__point__bar4
  .payment_main
    .center_box
      .regist-title
        支払い方法
      .card_number
        .box
          .box_in
            %label{for: "name"} カード番号
            %span.form-require 必須
            .form
            .icons
              = image_tag "cards.png", size: "343x49", alt: "カードのアイコン"
      .expiration_date
        %label{for: "name"} 有効期限
        %span.form-require 必須
        .expiration_day_year
          .year
          %h2年
        .expiration_day_month
          .month
          %h2月
        .security_code
          .in_box
            .in_block
              %label{for: "name"} セキュリティーコード
              %span.form-require 必須
              .code_box
              %h3カード裏面の番号とは
              %h3.blue__question?
      = link_to 'http://localhost:3000/signup/registration_data5' do
        .next_btn
          %button.u-box.btn-red{type: "submit"} 次へ進む  
  .footer      
    .footer_center
      プライバシーポリシー メルカリ利用規約 特定商取引
      .gray
        =link_to root_path do
          = image_tag "logo_gray.svg", size: "80x65", alt: "フリマのアイコン"
      .inc © Mercari, Inc.

app/views/signup/ragistration_data5.html.haml
.content
  .five_stage_header
    .logo-box
      .logo-box__logo
        =link_to root_path do
          = image_tag "fmarket_logo_red.svg", size: "185x49", alt: "フリマのアイコン"
      .logo-box__logo2
        .logo-box__logo2__text
          .logo-box__logo2__text__text1
            会員情報
          .logo-box__logo2__text__text2
            電話番号承認
          .logo-box__logo2__text__text3
            お届け先住所入力
          .logo-box__logo2__text__text4
            支払い方法
          .logo-box__logo2__text__text5
            完了
        .logo-box__logo2__point
          .logo-box__logo2__point__point1
          .logo-box__logo2__point__point2
          .logo-box__logo2__point__point3
          .logo-box__logo2__point__point4
          .logo-box__logo2__point__point5
          .logo-box__logo2__point__bar1
          .logo-box__logo2__point__bar2
          .logo-box__logo2__point__bar3
          .logo-box__logo2__point__bar4
  .regist_main
    .center_box
      .done-title
        会員登録完了
      .done__message
        .h1
          %h1ありがとうございます。
          %h1会員登録が完了しました。
        .next_btn
        = link_to 'http://localhost:3000/' do
          %button.u-box.btn-red{type: "submit"} メルカリをはじめる
        .image
          = link_to 'http://localhost:3000/signup/index' do
            = image_tag "startfmarket.png", size: "420x420", alt: "フリマスタート"
  .footer      
    .footer_center
      プライバシーポリシー メルカリ利用規約 特定商取引
      .gray
        =link_to root_path do
          = image_tag "logo_gray.svg", size: "80x65", alt: "フリマのアイコン"
      .inc © Mercari, Inc.

app/views/signup/registration_address.html.haml
.content
  .third__stage__header
    .logo-box
      .logo-box__logo
        =link_to root_path do
          = image_tag "fmarket_logo_red.svg", size: "185x49", alt: "フリマのアイコン"
      .logo-box__logo2
        .logo-box__logo2__text
          .logo-box__logo2__text__text1
            会員情報
          .logo-box__logo2__text__text2
            電話番号承認
          .logo-box__logo2__text__text3
            お届け先住所入力
          .logo-box__logo2__text__text4
            支払い方法
          .logo-box__logo2__text__text5
            完了
        .logo-box__logo2__point
          .logo-box__logo2__point__point1
          .logo-box__logo2__point__point2
          .logo-box__logo2__point__point3
          .logo-box__logo2__point__point4
          .logo-box__logo2__point__point5
          .logo-box__logo2__point__bar1
          .logo-box__logo2__point__bar2
          .logo-box__logo2__point__bar3
          .logo-box__logo2__point__bar4
  .center
    = form_for @user, url: {controller: 'signup', action: 'create'} do |f|
      .center__content
        .top
          %h2住所入力
        .main
          .main__text
            .main__text__top
              %labelお名前
              %span必須
              = f.text_field :family_name,placeholder: "例）山田",class: "main__text__top__box"
              = f.text_field :first_name,placeholder: "例）綾",class: "main__text__top__bottom"
            .main__text__top
              %labelお名前カナ
              %span必須
              = f.text_field :j_family_name,placeholder: "例）ヤマダ",class: "main__text__top__box"
              = f.text_field :j_first_name,placeholder: "例）アヤ",class: "main__text__top__bottom"
            = f.fields_for :address do |a|
              .main__text__top
                %label郵便番号
                %span必須
                = a.text_field :postal_code,placeholder: "例）123-4567",class: "main__text__top__bottom"
              .main__text__top
                %label都道府県
                %span必須
                = a.text_field :prefectuer,placeholder: "例）北海道",class: "main__text__top__bottom"
              .main__text__top
                %label市区町村
                %span必須
                = a.text_field :city_ward,placeholder: "例）横浜市緑区",class: "main__text__top__bottom"
              .main__text__top
                %label番地
                %span必須
                = a.text_field :address,placeholder: "例）青山1-1-1",class: "main__text__top__bottom"
              .main__text__top
                %label建物名
                %span.place任意
                = a.text_field :building,placeholder: "例）柳ビル103",class: "main__text__top__bottom"
              .main__text__top
                %label電話
                %span.place任意
                = a.phone_field :tel,placeholder: "例）1234567890",class: "main__text__top__bottom"
            = f.submit "次へ進む",class:"main__text__btn"
  .footer
    .footer_center
      プライバシーポリシー Fmarket利用規約 特定商取引
      .gray
        =link_to root_path do
          = image_tag "logo_gray.svg", size: "80x65", alt: "フリマのアイコン"
      .inc © Fmarket, Inc.

app/views/signup/registration_card.html.haml
.content
  .fourth__stage__header
    .logo-box
      .logo-box__logo
        = link_to root_path do
          = image_tag "fmarket_logo_red.svg", size: "185x49", alt: "フリマのアイコン"
      .logo-box__logo2
        .logo-box__logo2__text
          .logo-box__logo2__text__text1
            会員情報
          .logo-box__logo2__text__text2
            電話番号承認
          .logo-box__logo2__text__text3
            お届け先住所入力
          .logo-box__logo2__text__text4
            支払い方法
          .logo-box__logo2__text__text5
            完了
        .logo-box__logo2__point
          .logo-box__logo2__point__point1
          .logo-box__logo2__point__point2
          .logo-box__logo2__point__point3
          .logo-box__logo2__point__point4
          .logo-box__logo2__point__point5
          .logo-box__logo2__point__bar1
          .logo-box__logo2__point__bar2
          .logo-box__logo2__point__bar3
          .logo-box__logo2__point__bar4
  .payment_main
    .center_box
      .regist-title
        支払い方法
      .card_number
        .box
          .box_in
            %label{for: "name"} カード番号
            %span.form-require 必須
            .form
            .icons
              = image_tag "cards.png", size: "343x49", alt: "カードのアイコン"
      .expiration_date
        %label{for: "name"} 有効期限
        %span.form-require 必須
        .expiration_day_year
          .year
          %h2年
        .expiration_day_month
          .month
          %h2月
        .security_code
          .in_box
            .in_block
              %label{for: "name"} セキュリティーコード
              %span.form-require 必須
              .code_box
              %h3カード裏面の番号とは
              %h3.blue__question?
      = link_to registration_done_path do
        .next_btn
          %button.u-box.btn-red{type: "submit"} 次へ進む  
  .footer      
    .footer_center
      プライバシーポリシー Fmarket利用規約 特定商取引
      .gray
        = link_to root_path do
          = image_tag "logo_gray.svg", size: "80x65", alt: "フリマのアイコン"
      .inc © Fmarket, Inc.

app/views/signup/registration_done.html.haml
.content
  .five_stage_header
    .logo-box
      .logo-box__logo
        = link_to root_path do
          = image_tag "fmarket_logo_red.svg", size: "185x49", alt: "フリマのアイコン"
      .logo-box__logo2
        .logo-box__logo2__text
          .logo-box__logo2__text__text1
            会員情報
          .logo-box__logo2__text__text2
            電話番号承認
          .logo-box__logo2__text__text3
            お届け先住所入力
          .logo-box__logo2__text__text4
            支払い方法
          .logo-box__logo2__text__text5
            完了
        .logo-box__logo2__point
          .logo-box__logo2__point__point1
          .logo-box__logo2__point__point2
          .logo-box__logo2__point__point3
          .logo-box__logo2__point__point4
          .logo-box__logo2__point__point5
          .logo-box__logo2__point__bar1
          .logo-box__logo2__point__bar2
          .logo-box__logo2__point__bar3
          .logo-box__logo2__point__bar4
.regist_main
  .center_box
    .done-title
      会員登録完了
    .done__message
      .h1
        %h1ありがとうございます。
        %h1会員登録が完了しました。
      .next_btn
      =link_to root_path do
        %button.u-box.btn-red{type: "submit"} メルカリをはじめる
      .image
        =link_to root_path do
          = image_tag "startfmarket.png", size: "420x420", alt: "フリマスタート"
.footer      
  .footer_center
    プライバシーポリシー Fmarket利用規約 特定商取引
    .gray
      = link_to root_path do
        = image_tag "logo_gray.svg", size: "80x65", alt: "フリマのアイコン"
    .inc © Fmarket, Inc.

app/views/signup/step2.html.haml
.content
  .second__stage__header
    .logo-box
      .logo-box__logo
        =link_to root_path do
          = image_tag "fmarket_logo_red.svg", size: "185x49", alt: "フリマのアイコン"
      .logo-box__logo2
        .logo-box__logo2__text
          .logo-box__logo2__text__text1
            会員情報
          .logo-box__logo2__text__text2
            電話番号承認
          .logo-box__logo2__text__text3
            お届け先住所入力
          .logo-box__logo2__text__text4
            支払い方法
          .logo-box__logo2__text__text5
            完了
        .logo-box__logo2__point
          .logo-box__logo2__point__point1
          .logo-box__logo2__point__point2
          .logo-box__logo2__point__point3
          .logo-box__logo2__point__point4
          .logo-box__logo2__point__point5
          .logo-box__logo2__point__bar1
          .logo-box__logo2__point__bar2
          .logo-box__logo2__point__bar3
          .logo-box__logo2__point__bar4
  .center
    = form_for @user, url: step3_signup_index_path, method: :get, html: {class: "first-main__box__main__form"} do |f|
      .center__content
        .top
          %h2電話番号の確認
        .main
          .main__text
            .main__text__top
              %h2携帯電話の番号
              = f.phone_field :phonennumber,placeholder: "携帯電話の番号を入力",class: "main__text__top__box"
            %p本人確認のため、携帯電話のSMS(ショートメッセージービス)を利用して認証を行います。
            = f.submit "SMSを送信する",class:"main__text__btn"
            %p※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
            .main__text__bottom
              = link_to root_path, class: "info" do
                電話番号の確認が必要な理由
                = icon("fas", "chevron-right",class: "arrow")
                %span<>  
  .footer
    .footer_center
      プライバシーポリシー メルカリ利用規約 特定商取引
      .gray
        =link_to root_path do
          = image_tag "logo_gray.svg", size: "80x65", alt: "フリマのアイコン"
      .inc © Mercari, Inc.