config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      sessions: 'users/sessions',
      registrations: "signup",
      omniauth_callbacks: 'users/omniauth_callbacks'
    }
  devise_scope :user do
    get 'registration_index', to: 'signup#index'
    get 'registration_nickname', to: 'signup#registration_nickname'
    get 'registration_sms', to: 'signup#registration_sms'
    get 'registration_address', to: 'signup#registration_address'
    get 'registration_card', to: 'signup#registration_card'
    get 'registration_done', to: 'signup#registration_done'
  end


  root "products#index"
  resources :products do
    member do
      get 'purchase'
      get 'purchase_done'
      get 'buy', to: 'products#buy'
      get 'done', to: 'products#done'
    end
  end
    
  # resources :signup do
  #   collection do
  #     get 'registration_nickname'
  #     get 'registration_sms'
  #     get 'registration_address'
  #     get 'registration_card'
  #     get 'registration_done'
  #   end
  # end

  resources :mypages do
    collection do
      get 'credit'
      get 'exhibition'
      get 'identification'
      get 'logout'
      get 'profile'
    end
  end

  resources :cards do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

  resources :purchases do
    member do
      post 'pay', to: 'purchases#pay'
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
  
  validates :postal_code, presence: true
  validates :prefectuer, presence: true
  validates :city_ward, presence: true
  validates :address, presence: true
end

app/models/area.rb
class Area < ApplicationRecord
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  has_many :pay
end

app/models/category.rb
class Category < ApplicationRecord
  has_many  :products
  has_ancestry
end

app/models/condition.rb
class Condition < ApplicationRecord
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :src, ImageUploader
  belongs_to :product

  validates :src,               presence: true
end

app/models/pay.rb
class Pay < ApplicationRecord
  belongs_to :user
  belongs_to :card
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images, inverse_of: :product, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true  
  belongs_to :category
  belongs_to :seller, class_name: "User"
  belongs_to :buyer, class_name: "User", optional: true

  validates :seller_id, :name, :discription, :category_id, :state, :delivery_fee, :sending_method, :sending_area, :sending_day, :price, presence: true

end

app/models/sending_method.rb
class SendingMethod < ApplicationRecord
end

app/models/signup.rb
class Signup < ApplicationRecord
end

app/models/size.rb
class Size < ApplicationRecord
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  # associations
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  
  has_one :address
  has_many :card
  accepts_nested_attributes_for :address
  has_many :products
  has_many :sns_credentials, dependent: :destroy

  #↓うまくいかないので後程
#   has_many :seller_products, class_name: 'Product', :foreign_key => 'seller_id'
#   has_many :buyer_products, class_name: 'Product', :foreign_key => 'buyer_id'

       # バリデーション　↓うまくいかないので後程
       VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
       VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
       validates :nickname,                presence: true, length: {maximum: 20}
      #  validates :email,                   {presence: true, format: { with: VALID_EMAIL_REGEX }}
       validates :email,               presence: true
       validates :family_name,               presence: true
       validates :first_name,              presence: true
       validates :j_family_name,          presence: true
       validates :j_first_name,         presence: true
       validates :birthday_year,          numericality: true
       validates :birthday_month,         numericality: true
       validates :birthday_day,           numericality: true
       validates :phonennumber,            {presence: true, format: { with: VALID_PHONE_REGEX }}

  def self.from_omniauth(auth)
       sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
       # sns認証したことがあればアソシエーションで取得
       # 無ければemailでユーザー検索して取得orビルド(保存はしない)
       user = sns.user || User.where(email: auth.info.email).first_or_initialize(
         nickname: auth.info.name,
           email: auth.info.email
       )
       # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
       if user.persisted?
         sns.user = user
         sns.save
       end
       user
  end
  
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController

  def index
    @user = User.find(current_user[:id])
  end

  def new
  end

  def create
    
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/mypages/_left-menu.html.haml
%nav.user-mypage-content__left__menu
  %ul.user-mypage-content__left__menu__list
    %li.user-mypage-content__left__menu__list__box
      = link_to mypages_path, class: "user-mypage-content__left__menu__list__box__item#{' active' if current_page?(mypages_path)}" do
        = icon('fas', 'chevron-right', class:'icon')
        マイページ
    %li.user-mypage-content__left__menu__list__box
      = link_to root_path, class: "user-mypage-content__left__menu__list__box__item" do
        = icon('fas', 'chevron-right', class:'icon')
        お知らせ
    %li.user-mypage-content__left__menu__list__box
      = link_to root_path, class: "user-mypage-content__left__menu__list__box__item" do
        = icon('fas', 'chevron-right', class:'icon')
        やることリスト
    %li.user-mypage-content__left__menu__list__box
      = link_to root_path, class: "user-mypage-content__left__menu__list__box__item" do
        = icon('fas', 'chevron-right', class:'icon')
        いいね！一覧
    %li.user-mypage-content__left__menu__list__box
      = link_to root_path, class: "user-mypage-content__left__menu__list__box__item" do
        = icon('fas', 'chevron-right', class:'icon')
        出品する
    %li.user-mypage-content__left__menu__list__box
      = link_to root_path, class: "user-mypage-content__left__menu__list__box__item" do
        = icon('fas', 'chevron-right', class:'icon')
        出品した商品 - 出品中
    %li.user-mypage-content__left__menu__list__box
      = link_to root_path, class: "user-mypage-content__left__menu__list__box__item" do
        = icon('fas', 'chevron-right', class:'icon')
        出品した商品 - 取引中
    %li.user-mypage-content__left__menu__list__box
      = link_to root_path, class: "user-mypage-content__left__menu__list__box__item" do
        = icon('fas', 'chevron-right', class:'icon')
        出品した商品 - 売却済み
    %li.user-mypage-content__left__menu__list__box
      = link_to root_path, class: "user-mypage-content__left__menu__list__box__item" do
        = icon('fas', 'chevron-right', class:'icon')
        購入した商品 - 取引中
    %li.user-mypage-content__left__menu__list__box
      = link_to root_path, class: "user-mypage-content__left__menu__list__box__item" do
        = icon('fas', 'chevron-right', class:'icon')
        購入した商品 - 過去の取引
    %li.user-mypage-content__left__menu__list__box
      = link_to root_path, class: "user-mypage-content__left__menu__list__box__item" do
        = icon('fas', 'chevron-right', class:'icon')
        ニュース一覧
    %li.user-mypage-content__left__menu__list__box
      = link_to root_path, class: "user-mypage-content__left__menu__list__box__item" do
        = icon('fas', 'chevron-right', class:'icon')
        評価一覧
    %li.user-mypage-content__left__menu__list__box
      = link_to root_path, class: "user-mypage-content__left__menu__list__box__item" do
        = icon('fas', 'chevron-right', class:'icon')
        ガイド
    %li.user-mypage-content__left__menu__list__box
      = link_to root_path, class: "user-mypage-content__left__menu__list__box__item" do
        = icon('fas', 'chevron-right', class:'icon')
        お問い合わせ
  %h3.user-mypage-content__left__menu__head
    メルペイ
  %ul.user-mypage-content__left__menu__list
    %li.user-mypage-content__left__menu__list__box
      = link_to root_path, class: "user-mypage-content__left__menu__list__box__item" do
        = icon('fas', 'chevron-right', class:'icon')
        売上・振込申請
    %li.user-mypage-content__left__menu__list__box
      = link_to root_path, class: "user-mypage-content__left__menu__list__box__item" do
        = icon('fas', 'chevron-right', class:'icon')
        ポイント
  %h3.user-mypage-content__left__menu__head
    設定
  %ul.user-mypage-content__left__menu__list
    %li.user-mypage-content__left__menu__list__box
      = link_to profile_mypages_path, class: "user-mypage-content__left__menu__list__box__item#{' active' if current_page?(profile_mypages_path)}" do
        = icon('fas', 'chevron-right', class:'icon')
        プロフィール
    %li.user-mypage-content__left__menu__list__box
      = link_to root_path, class: "user-mypage-content__left__menu__list__box__item" do
        = icon('fas', 'chevron-right', class:'icon')
        発送元・お届け先住所変更
    %li.user-mypage-content__left__menu__list__box
      - if controller.controller_name == "mypages"
        = link_to credit_mypages_path, class: "user-mypage-content__left__menu__list__box__item#{' active' if current_page?(credit_mypages_path)}" do
          = icon('fas', 'chevron-right', class:'icon')
          支払い方法
      - elsif controller.controller_name == "cards"
        = link_to credit_mypages_path, class: "user-mypage-content__left__menu__list__box__item#{' active' if current_page?(new_card_path)||current_page?(card_path)}" do
          = icon('fas', 'chevron-right', class:'icon')
          支払い方法
    %li.user-mypage-content__left__menu__list__box
      = link_to root_path, class: "user-mypage-content__left__menu__list__box__item" do
        = icon('fas', 'chevron-right', class:'icon')
        メール/パスワード
    %li.user-mypage-content__left__menu__list__box
      = link_to identification_mypages_path, class: "user-mypage-content__left__menu__list__box__item#{' active' if current_page?(identification_mypages_path)}" do
        = icon('fas', 'chevron-right', class:'icon')
        本人情報
    %li.user-mypage-content__left__menu__list__box
      = link_to root_path, class: "user-mypage-content__left__menu__list__box__item" do
        = icon('fas', 'chevron-right', class:'icon')
        電話番号の確認
    %li.user-mypage-content__left__menu__list__box
      = link_to logout_mypages_path, class: "user-mypage-content__left__menu__list__box__item#{' active' if current_page?(logout_mypages_path)}" do
        = icon('fas', 'chevron-right', class:'icon')
        ログアウト

app/views/mypages/_right-body.html.haml
.user-mypage-content__right__body
  .content  
    = image_tag "user-bg.jpg", alt: "img", class: "content"
    = link_to root_path, class: "user-exhibition"  do
      .content__user
        = image_tag "user.jpg", alt: "user-img", class: "user"
      .content__name 
        = @user.nickname
      .content__number
        %div
          評価
          %span.count 0
        %div
          出品数
          %span.count 0
  .mypage
    %ul.tab
      %li.select お知らせ
      %li やることリスト
    .mypage__tabs-list
      %ul.contents
        %li{style: "display: block;"}
          = link_to root_path, class: "list-link"  do
            .figure
              = image_tag "logo_red.svg", class: "logo"
            .list-body
              .list-body__text
                左だよ。おはよう
              .list-body__time
                = icon( "far", "clock", class: "clock")
                %span 1 時間前
            = icon("fas", "chevron-right", class: "chevron")
        %li{style: "display: none;"}
          = link_to root_path, class: "list-link"  do
            .figure
              = image_tag "logo_red.svg", class: "logo"
            .list-body
              .list-body__text
                右だよ。こんばんは
              .list-body__time
                = icon( "far", "clock", class: "clock")
                %span 6 時間前
            = icon("fas", "chevron-right", class: "chevron")
    .mypage__bottom
      = link_to "一覧を見る", "/", class: "list-view"
  .bottom
    .bottom__head
      購入した商品
    %ul.tabs
      %li.current 取引中
      %li 過去の取引
    .bottom__list
      %ul.content
        %li
          .test1
            = image_tag "logo_gray.svg", class: "logo"
          .test
            取引中の商品がありません
        %li.hide
          .test1
            = image_tag "logo_gray.svg", class: "logo"
          .test
            過去に取引した商品がありません

app/views/mypages/credit.html.haml
%header.priducts-toppage-header
  - if flash[:notice]
    .flash
      = flash[:notice]
  = render 'products/header'
.breadcrumb
  = render 'shared/breadcrumbs_credit'
.user-mypage-content
  .user-mypage-content__left
    = render 'left-menu'
  .user-mypage-content__right
    .user-mypage-content__right__top
      支払い方法
    .user-mypage-content__right__box
      .user-mypage-content__right__box__in
        .user-mypage-content__right__box__in__red-box
          .icon
            %i.far.fa-credit-card
          .card-link
            = link_to 'クレジットカードを追加する',cards_path,class:'card-link'
      .user-mypage-content__right__box__int
        = link_to "支払い方法について",'',class:'pay-text'
        .user-mypage-content__right__box__int__arrow
          %i.fas.fa-chevron-right
  .clearfix
.products-toppage-footer-app
  = render 'products/footer-app'
%footer.products-toppage-footer-company
  = render 'products/footer-company'
.exhibition-btn
  = render 'products/exhibition-btn'

app/views/mypages/exhibition.html.haml
%header.priducts-toppage-header
  = render 'products/header'
.breadcrumb
  = render 'shared/breadcrumbs_exhibition'
.user-mypage-content
  .user-mypage-content__left
    = render 'left-menu-exhibition'
  .user-mypage-content__right
    .mypage-tab-head
      購入した商品
    %ul.tabs
      %li 出品中
      %li 取引中
      %li 売却済み
    .exhibition-list
      %ul.content
        %li{style: "display: block;"}
          = link_to root_path, class: "list-link"  do
            .figure
              = image_tag "logo_red.svg", class: "logo"
            .list-body
              .list-body__text
                商品名
              .list-body__time
                = icon( "far", "clock", class: "clock")
            = icon("fas", "chevron-right", class: "chevron")
        %li{style: "display: none;"}
          a
        %li{style: "display: none;"}
          a
  .clearfix
.products-toppage-footer-app
  = render 'products/footer-app'
%footer.products-toppage-footer-company
  = render 'products/footer-company'
.exhibition-btn
  = render 'products/exhibition-btn'

app/views/mypages/identification.html.haml
%header.priducts-toppage-header
  = render 'products/header'
.breadcrumb
  = render 'shared/breadcrumbs_identification'
.user-mypage-content
  .user-mypage-content__left
    = render 'left-menu'
  .user-mypage-content__right
    .user-mypage-content__right__top
      本人情報の登録
    .user-mypage-content__right__content
      .user-mypage-content__right__content__text
        お客さまの本人情報をご登録ください。
        %br
        登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
      .user-mypage-content__right__content__link1
        本人確認書類のアップロードについて＞
      .user-mypage-content__right__content__name-label
        お名前
        .user-mypage-content__right__content__name-label__form1
          坂上　真太朗
      .user-mypage-content__right__content__j-name
        お名前カナ
        .user-mypage-content__right__content__j-name__form2
          サカウエ　シンタロウ
      .user-mypage-content__right__content__birthday
        年月日
        .user-mypage-content__right__content__birthday__form3
          1985/9/15
      .user-mypage-content__right__content__postal-code
        .user-mypage-content__right__content__postal-code__title
          郵便番号
        .user-mypage-content__right__content__postal-code__option
          任意
        .user-mypage-content__right__content__postal-code__form4
          例)12345678
      .user-mypage-content__right__content__prefecture
        .user-mypage-content__right__content__prefecture__title
          都道府県
        .user-mypage-content__right__content__prefecture__option
          任意
        .user-mypage-content__right__content__prefecture__form5
          神奈川県
      .user-mypage-content__right__content__municipalities
        .user-mypage-content__right__content__municipalities__title
          市区町村
        .user-mypage-content__right__content__municipalities__option
          任意
        .user-mypage-content__right__content__municipalities__form6
          例)横浜
      .user-mypage-content__right__content__address
        .user-mypage-content__right__content__address__title
          番地
        .user-mypage-content__right__content__address__option
          任意
        .user-mypage-content__right__content__address__form7
          例)青山
      .user-mypage-content__right__content__building
        .user-mypage-content__right__content__building__title
          建物名
        .user-mypage-content__right__content__building__option
          任意
        .user-mypage-content__right__content__building__form8
          例)柳マンション
      .user-mypage-content__right__content__send-btn
        = link_to '登録する', root_path,class:'btn'
      .user-mypage-content__right__content__link2
        = link_to '本人情報の登録について＞',root_path,class:'b'
  .clearfix
.products-toppage-footer-app
  = render 'products/footer-app'
%footer.products-toppage-footer-company
  = render 'products/footer-company'
.exhibition-btn
  = render 'products/exhibition-btn'

app/views/mypages/index.html.haml
%header.priducts-toppage-header
  = render 'products/header'
.breadcrumb
  = render 'shared/breadcrumbs'
  .clearfix
.user-mypage-content
  .user-mypage-content__left
    = render 'left-menu'
  .user-mypage-content__right
    = render 'right-body'
  .clearfix
.products-toppage-footer-app
  = render 'products/footer-app'
%footer.products-toppage-footer-company
  = render 'products/footer-company'
.exhibition-btn
  = render 'products/exhibition-btn'

app/views/mypages/logout.html.haml
%header.priducts-toppage-header
  = render 'products/header'
.breadcrumb
  = render 'shared/breadcrumbs_logout'
.user-mypage-content
  .user-mypage-content__left
    = render 'left-menu'
  .user-mypage-content__right2
    .user-mypage-content__right2__center-btn2
      = link_to "ログアウト", destroy_user_session_path, method: :delete,class:'btn2'
  .clearfix
.products-toppage-footer-app
  = render 'products/footer-app'
%footer.products-toppage-footer-company
  = render 'products/footer-company'
.exhibition-btn
  = render 'products/exhibition-btn'

app/views/mypages/new.html.haml
%header.priducts-toppage-header
  = render 'products/header'
.breadcrumb
  = render 'shared/breadcrumbs_logout'

.user-mypage-content
  .user-mypage-content__left
    = render 'left-menu-logout'

.content__title
  %h2 クレジットカード情報入力
.content__credit-card
  .content__credit-card__inner
    = form_for url: cards_path, method: :post, html: { name: "inputForm" } do |f| -# createアクションのパスを指定
      = f.label :カード番号, class: 'label'
      %span 必須
      = f.text_field :card_number, type: 'text', class: 'input-number', placeholder: '半角数字のみ', maxlength: "16"
      .cards-expire
        = f.label :有効期限, class: 'label'
        %span 必須
        %br
        .cards-expire__wrap
          = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'input-expire'
          %span.expire-text 月
          %br
        .cards-expire__wrap
          = f.select :exp_year, [["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'input-expire'
          %span.expire-text 年
      .cards-expire
        = f.label :セキュリティコード, class: 'label'
        %span 必須
        = f.text_field :cvc, type: 'text', class: 'input-number', placeholder: 'カード背面4桁もしくは3桁の番号', maxlength: "4"
      .content-bottom#card_token
        = f.submit '追加する', class: 'content-bottom--add-btn', id: 'token_submit'

-# .payment_main
-#   .center_box
-#     .regist-title
-#       支払い方法
-#     .card_number
-#       .box
-#         .box_in
-#           %label{for: "name"} カード番号
-#           %span.form-require 必須
-#           .form
-#             = form_for @pay, url:'pay_path' do|f|
-#               = f.text_field :number, class:'number', placeholder: 'type a number' do
-#           .icons
-#             = image_tag "cards.png", size: "343x49", alt: "カードのアイコン"
-#               .send-space
-#                 .send-space__btn
-#                   =  f.submit '登録'
-#     .expiration_date
-#       %label{for: "name"} 有効期限
-#       %span.form-require 必須
-#       .expiration_day_year
-#         .year
-#         %h2年
-#       .expiration_day_month
-#         .month
-#         %h2月
-#       .security_code
-#         .in_box
-#           .in_block
-#             %label{for: "name"} セキュリティーコード
-#             %span.form-require 必須
-#             .code_box
-#             %h3カード裏面の番号とは
  .clearfix
.products-toppage-footer-app
  = render 'products/footer-app'
%footer.products-toppage-footer-company
  = render 'products/footer-company'
.exhibition-btn
  = render 'products/exhibition-btn'

app/views/mypages/profile.html.haml
%header.priducts-toppage-header
  = render 'products/header'
.breadcrumb
  = render 'shared/breadcrumbs_profile'
.user-mypage-content
  .user-mypage-content__left
    = render 'left-menu'
  .user-mypage-content__right
    .user-mypage-content__right__top
      プロフィール
    .profileimg  
      = image_tag "user-bg.jpg", alt: "img", class: "clearimg"
      .profileimg__body
        .profileimg__body__image
          = image_tag "member_photo_noimage_thumb.png", alt: "img", class: "imageicon"
        .profileimg__body__name
          = current_user.nickname
    .profile
      .profile__text
        %p 閲覧ありがとうございます
      .profile__btn
        %p 変更する
  .clearfix
.products-toppage-footer-app
  = render 'products/footer-app'
%footer.products-toppage-footer-company
  = render 'products/footer-company'
.exhibition-btn
  = render 'products/exhibition-btn'