config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      sessions: 'users/sessions',
      registrations: "signup",
      omniauth_callbacks: 'users/omniauth_callbacks'
    }
  devise_scope :user do
    get 'registration_index', to: 'signup#index'
    get 'registration_nickname', to: 'signup#registration_nickname'
    get 'registration_sms', to: 'signup#registration_sms'
    get 'registration_address', to: 'signup#registration_address'
    get 'registration_card', to: 'signup#registration_card'
    get 'registration_done', to: 'signup#registration_done'
  end


  root "products#index"
  resources :products do
    member do
      get 'purchase'
      get 'purchase_done'
      get 'buy', to: 'products#buy'
      get 'done', to: 'products#done'
    end
  end
    
  # resources :signup do
  #   collection do
  #     get 'registration_nickname'
  #     get 'registration_sms'
  #     get 'registration_address'
  #     get 'registration_card'
  #     get 'registration_done'
  #   end
  # end

  resources :mypages do
    collection do
      get 'credit'
      get 'exhibition'
      get 'identification'
      get 'logout'
      get 'profile'
    end
  end

  resources :cards do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

  resources :purchases do
    member do
      post 'pay', to: 'purchases#pay'
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images, inverse_of: :product, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true  
  belongs_to :category
  belongs_to :seller, class_name: "User"
  belongs_to :buyer, class_name: "User", optional: true

  validates :seller_id, :name, :discription, :category_id, :state, :delivery_fee, :sending_method, :sending_area, :sending_day, :price, presence: true

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_login, except: [:index, :show]
  before_action :set_product, except: [:index, :new, :create]
  before_action :seller_id_is_current_user_id, only: [:edit, :update, :destroy]

  require 'payjp'

  def index
      @ladies = Product.includes(:images).where(category_id: 1).order("created_at DESC").limit(10)
      @mens = Product.includes(:images).where(category_id: 2).order("created_at DESC").limit(10)
  end

  def show
    # product_tableの1つの情報を渡す
    # image_tableのproduct_idのカラムがproduct_tableのidと一致した情報
    @images = Image.where(product_id: @product.id)
    # user_tableの主キーとproduct_tableのseller_idが一致した情報を渡す
    @user = User.find_by(id: @product.seller_id)
  end

  def new
      @product = Product.new
      @product.images.new
  end

  def create
    @product = Product.new(product_params)
    if @product.images == [] || @product.images.ids == [nil]
      redirect_to :back
      flash[:notice] = "必ず画像を1枚以上選択して下さい。"
    else
      if @product.save!
        redirect_to root_path
      else
        redirect_to :back
      end
    end
  end

  def edit
  end 

  def update
      if @product.images == [] || @product.images.ids == [nil]
        redirect_to :back
        flash[:notice] = "必ず画像を1枚以上選択して下さい。"
      else
        @product.update(product_params)
        redirect_to root_path
      end
  end

  def purchase
    if @product.buyer_id == nil
      if current_user.id != @product.seller_id
        Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
        @images = Image.where(product_id: @product.id)
        @address= Address.find_by(user_id: current_user.id)
        card = Card.where(user_id: current_user.id).first
        @cards = Card.find_by(user_id: current_user.id)
        if card
          customer = Payjp::Customer.retrieve(card.customer_id)
          @default_card_information = customer.cards.retrieve(card.card_id)
        else
          redirect_to credit_mypages_path
          flash[:notice] = "クレジットカード登録をして下さい"
        end
      else
        redirect_to root_path
        flash[:notice] = "自分の商品は購入できません"
      end
    else
      redirect_to root_path
      flash[:notice] = "この商品は、既に売却済です"
    end
  end

  def destroy
    @product.destroy
    redirect_to root_path
    flash[:notice] = "商品を削除しました"
  end

  def done
    @product.buyer_id = current_user.id
    if @product.save!
      # 別コントローラー(purchases_controllerのdef pay)で、products内のdone.haml.htmlを読むように指示している。
      # そのため、ここでは何も指示をしなくても、問題ないと思われる(正常動作する)
      # 処理の流れ：別コントローラーでpayjpの処理を行う→このdefで、buyer_id = current_user.id後、@product.save!を行う → done.haml.htmlが表示される
    else
      render :purchase
    end
  end
  
  private

  def product_params
    params.require(:product).permit(:seller_id, :name, :discription, :category_id, :brand, :state, :delivery_fee, :sending_method, :sending_area, :sending_day, :price, images_attributes:  [:src, :_destroy, :id]).merge(seller_id: current_user.id)
  end
  
  def set_product
    @product = Product.find(params[:id])
  end

  def require_login
    unless user_signed_in?
      redirect_to user_session_path
      flash[:notice] = "ログインをして下さい"
    end
  end

  def seller_id_is_current_user_id
    if current_user.id == @product.seller_id
      # 編集画面に遷移する
    else
      redirect_to root_path
      flash[:notice] = "自分の商品しか、編集・削除は行えません"
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_content.html.haml
.slider
  .slider__content
    = image_tag 'himawari.jpg'
  .slider__content
    = image_tag 'yakei.jpg'
  .slider__content
    = image_tag 'sougen.jpg'

.categoryname-sapce
  .categoryname-sapce__title
    人気のカテゴリ
  .categoryname-sapce__center-space
    .categoryname-sapce__center-space__name1
      レディース
    .categoryname-sapce__center-space__name2
      メンズ
    .categoryname-sapce__center-space__name3
      おもちゃ・ホビー・グッズ
    .categoryname-sapce__center-space__name4
      家電・スマホ・カメラ
.center
  .center__space-a
    .center__space-a__new-item1
      .center__space-a__new-item1__title1
        レディース新着アイテム
      .center__space-a__new-item1__link1
        = link_to "もっとみる"
      .center__space-a__new-item1__image-space
        .space
          - @ladies.each do |product|
            = link_to product_path(product) do
              .itembox
                .itembox__image
                  = image_tag product.images.first.src, size: "188x168"
                  .itembox__image__sold-mark
                    - if product.buyer_id != nil
                      = render 'sold'
                  .itembox__image__price
                    ¥
                    = product.price
                .itembox__title
                  = product.name
  .center__space-b
    .center__space-b__new-item2
      .center__space-b__new-item2__title2
        メンズ新着アイテム
      .center__space-b__new-item2__link2
        = link_to "もっとみる"
      .center__space-b__new-item2__image-space
        .space
          - @mens.each do |product|
            = link_to product_path(product) do
              .itembox
                .itembox__image
                  = image_tag product.images.first.src, size: "188x168"
                  .itembox__image__sold-mark
                    - if product.buyer_id != nil
                      = render 'sold'
                  .itembox__image__price
                    ¥
                    = product.price
                .itembox__title
                  = product.name

-#   .center__space-c
-#     .center__space-c__new-item3
-#       .center__space-c__new-item3__title3
-#         メンズ新着アイテム
-#       .center__space-c__new-item3__link3
-#         = link_to "もっとみる" , class:'links'
-#       .center__space-c__new-item3__image-space
-#         .center__space-c__new-item3__image-space__image
-#           ここは写真です
-#         .center__space-c__new-item3__image-space__imagetest
-#           testimage
-#   .center__space-d
-#     .center__space-d__new-item4
-#       .center__space-d__new-item4__title4
-#         家電・スマホ・カメラ新着アイテム
-#       .center__space-d__new-item4__link4
-#         = link_to "もっとみる" , class:'links'
-#       .center__space-d__new-item4__image-space
-#         .center__space-d__new-item4__image-space__image
-#           ここは写真です
-#         .center__space-d__new-item4__image-space__imagetest
-#           testimage
    
-#   .center__space-e
-#     .center__space-e__new-item5
-#       .center__space-e__new-item5__title5
-#         おもちゃ・ホビー・グッズ新着アイテム
-#       .center__space-e__new-item5__link5
-#         = link_to "もっとみる" , class:'links'
-#       .center__space-e__new-item5__image-space
-#         .center__space-e__new-item5__image-space__image
-#           ここは写真です
-#         .center__space-e__new-item5__image-space__imagetest
-#           testimage

-# .categoryname-sapce
-#   .categoryname-sapce__title
-#     人気のブランド
-#   .categoryname-sapce__center-space
-#     .categoryname-sapce__center-space__name5
-#       シャネル
-#     .categoryname-sapce__center-space__name6
-#       ルイビトン
-#     .categoryname-sapce__center-space__name7
-#       シュプリーム
-#     .categoryname-sapce__center-space__name8
-#       ナイキ
-# .center
-#   .center__space-a
-#     .center__space-a__new-item1
-#       .center__space-a__new-item1__title1
-#         シャネル新着アイテム
-#       .center__space-a__new-item1__link1
-#         = link_to "もっとみる"
-#       .center__space-a__new-item1__image-space
-#         .center__space-a__new-item1__image-space__image
-#           ここは写真です
-#         .center__space-a__new-item1__image-space__imagetest
-#           testimage
-#   .center__space-b
-#     .center__space-b__new-item2
-#       .center__space-b__new-item2__title2
-#         ルイビトン新着アイテム
-#       .center__space-b__new-item2__link2
-#         = link_to "もっとみる" , class:'links'
-#       .center__space-b__new-item2__image-space
-#         .center__space-b__new-item2__image-space__image
-#           ここは写真です
-#         .center__space-b__new-item2__image-space__imagetest
-#           testimage

-#   .center__space-c
-#     .center__space-c__new-item3
-#       .center__space-c__new-item3__title3
-#         シュプリーム新着アイテム
-#       .center__space-c__new-item3__link3
-#         = link_to "もっとみる" , class:'links'
-#       .center__space-c__new-item3__image-space
-#         .center__space-c__new-item3__image-space__image
-#           ここは写真です
-#         .center__space-c__new-item3__image-space__imagetest
-#           testimage
-#   .center__space-d
-#     .center__space-d__new-item4
-#       .center__space-d__new-item4__title4
-#         ナイキ新着アイテム
-#       .center__space-d__new-item4__link4
-#         = link_to "もっとみる" , class:'links'
-#       .center__space-d__new-item4__image-space
-#         .center__space-d__new-item4__image-space__image
-#           ここは写真です
-#         .center__space-d__new-item4__image-space__imagetest
-#           testimage
    
-#   .center__space-e
-#     .center__space-e__new-item5
-#       .center__space-e__new-item5__title5
-#         おもちゃ・ホビー・グッズ新着アイテム
-#       .center__space-e__new-item5__link5
-#         = link_to "もっとみる" , class:'links'
-#       .center__space-e__new-item5__image-space
-#         .center__space-e__new-item5__image-space__image
-#           ここは写真です
-#         .center__space-e__new-item5__image-space__imagetest
-#           testimage

app/views/products/_exhibition-btn.html.haml
= link_to new_product_path, class: "exhibition" do
  .exhibition__text-icon
    .exhibition__text-icon__text
      出品
    .exhibition__text-icon__icon
      = icon('fas','camera', class: 'icon')

app/views/products/_footer-app.html.haml
.footer_app
  = image_tag "tanbo.jpg", class:"footer_app"
  .footer_app__contents
    .footer_app__contents__left-content
      .footer_app__contents__left-content__top
        スマホでかんたんフリマアプリ
      .footer_app__contents__left-content__center 
        今すぐ無料ダウンロード！
      .footer_app__contents__left-content__bottom
        = image_tag 'logo_red.svg', alt: 'logo', class: 'flogo'
        = link_to image_tag("app_store.jpg", class:"app"),'https://apps.apple.com/jp/app/id667861049?l=ja', class:"app"
        = link_to image_tag("google_play.jpg", class:"google"),'https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja', class:"google"
    .footer_app__contents__right-content
      = image_tag 'cherry-blossom.jpg', class: 'footer_app__contents__right-content'

app/views/products/_footer-company.html.haml
.footer_company
  .footer_company__top-contents
    .footer_company__top-contents__about
      %h2.footer_company__top-contents__about__title
        Fmarketについて
      %ul.footer_company__top-contents__about__overview
        %li.overview
          = link_to '会社概要（運営会社）', 'http://google.co.jp',class: "naiyou"
        %li.overview
          = link_to '採用情報', 'http://google.co.jp',class: "naiyou"
        %li.overview
          = link_to 'プレスリリース', 'http://google.co.jp',class: "naiyou"
        %li.overview
          = link_to '公式ブログ', 'http://google.co.jp',class: "naiyou"
        %li.overview
          = link_to 'Fmarketロゴ利用ガイドライン', 'http://google.co.jp',class: "naiyou"
        .footer_company__top-contents__about__overview__icon
          .footer_company__top-contents__about__overview__icon__twitter
            = link_to 'https://twitter.com/mercari_jp',target:"_blank",class: "icon" do
              = icon('fab','twitter', class: 'twitter')
          .footer_company__top-contents__about__overview__icon__facebook
            = link_to 'https://www.facebook.com/mercarijp',class: "icon" do
              = icon('fab','facebook-square',target:"_blank", class: 'facebook') #targe:"_blankで別タブに表示"
    .footer_company__top-contents__help
      %h2.footer_company__top-contents__help__title
        ヘルプ＆ガイド
      %ul.footer_company__top-contents__help__overview
        %li.overview
          = link_to 'Fmarketガイド', 'http://google.co.jp',class: "naiyou"
        %li.overview
          = link_to 'らくらくフリマ便', 'http://google.co.jp',class: "naiyou"
        %li.overview
          = link_to 'ゆうゆうフリマ便', 'http://google.co.jp',class: "naiyou"
        %li.overview
          = link_to '大型フリマ便', 'http://google.co.jp',class: "naiyou"
        %li.overview
          = link_to '車体取引ガイド', 'http://google.co.jp',class: "naiyou"
        %li.overview
          = link_to 'Fmarketあんしん・あんぜん宣言！', 'http://google.co.jp',class: "naiyou"
        %li.overview
          = link_to '偽ブランド品撲滅への取り組み', 'http://google.co.jp',class: "naiyou"
        %li.overview
          = link_to 'Fmarketボックス', 'http://google.co.jp',class: "naiyou"
    .footer_company__top-contents__privacy
      %h2.footer_company__top-contents__privacy__title
        プライバシーと利用規約
      %ul.footer_company__top-contents__privacy__left-overview
        %li.overview
          = link_to 'プライバシーポリシー', 'http://google.co.jp',class: "naiyou"
        %li.overview
          = link_to 'Fmarket利用規約', 'http://google.co.jp',class: "naiyou"
        %li.overview
          = link_to 'あんしんスマホサポート制度に関する利用特約', 'http://google.co.jp',class: "naiyou"
        %li.overview
          = link_to 'コンプライアンスポリシー', 'http://google.co.jp',class: "naiyou"
      %ul.footer_company__top-contents__privacy__right-overview
        %li.overview
          = link_to '個人データの安全管理に係る基本方針', 'http://google.co.jp',class: "naiyou"
        %li.overview
          = link_to '特定商取引に関する表記', 'http://google.co.jp',class: "naiyou"
        %li.overview
          = link_to '資金決済法に基づく表示', 'http://google.co.jp',class: "naiyou"
        %li.overview
          = link_to '法令遵守と犯罪防止のために', 'http://google.co.jp',class: "naiyou"
    .footer_company__top-contents__country
      %h2.footer_company__top-contents__country__title
        国
      %ul.footer_company__top-contents__country__overview
        %li.overview
          = link_to '日本', 'http://google.co.jp',class: "naiyou"
        %li.overview
          = link_to 'United States', 'http://google.co.jp',class: "naiyou"
  .footer_company__last-content
    = link_to image_tag("logo_white.svg",width: 30, height: 30),'http://google.co.jp', class:"mercari"
    .footer_company__last-content__lnc
      © Fmarket, Inc.

app/views/products/_header.html.haml
.header
  .header__content
    .hd-top
      .hd-top__left
        = image_tag "fmarket_logo_red.svg", class: "img-logo"
      .hd-top__right
        .hd-top__right__icon
          = link_to "/", class: "normal" do
            = icon('fas', 'search', class: 'search')
    .hd-bottom
      .hd-bottom__left
        .hd-bottom__left__category
          = link_to "/", class: "bold" do
            = icon('fas', 'list-ul', class: 'icon')
            カテゴリーから探す
        .hd-bottom__left__bland
          = link_to "/", class: "bold" do
            = icon('fas', 'tag', class: 'icon')
            ブランドから探す
      .hd-bottom__right
        - if user_signed_in?
          .hd-bottom__right__info
            = link_to "/", class: "normal" do
              = icon('far', 'heart', class: 'ificon')
              いいね！一覧
          .hd-bottom__right__info
            = link_to "/", class: "normal" do
              = icon('far', 'bell', class: 'ificon')
              お知らせ
          .hd-bottom__right__info
            = link_to "/", class: "normal" do
              = icon('fas', 'check', class: 'ificongo')
              やることリスト
          .hd-bottom__right__info
            = link_to mypages_path, class: "normal" do
              マイページ
        - else
          .hd-bottom__right__new
            = link_to registration_index_path, class: "sign" do
              新規会員登録
          .hd-bottom__right__signup
            = link_to user_session_path, class: "login" do
              ログイン

app/views/products/_sold.html.haml
.itembox__image__sold-mark__sold
  .itembox__image__sold-mark__sold__inner
    SOLD

app/views/products/done.html.haml
.purchase-done-content
  .header-content
    = link_to root_path do
      = image_tag "fmarket_logo_red.svg", size: "185x49", alt: "フリマのアイコン"
  .second-content
    %h2 購入が完了しました
  .regist_main
    .center_box
      .done__message
        .back-btn
          =link_to root_path do
            %button.btn{type: "submit"} マイページへ戻る
  .footera
    .footer-centera
      プライバシーポリシー Fmarket利用規約 特定商取引
      .gray
        = link_to root_path do
          = image_tag "logo_gray.svg", size: "80x65", alt: "フリマのアイコン"
      .inc © Fmarket, Inc.

app/views/products/index.html.haml
%header.priducts-toppage-header
  - if flash[:notice]
    .flash
      = flash[:notice]
  = render 'header' 
.products-toppage-contents
  = render 'content'
.products-toppage-footer-app
  = render 'footer-app'
%footer.products-toppage-footer-company
  = render 'footer-company'
.exhibition-btn
  = render 'exhibition-btn'
  

app/views/products/purchase.html.haml
.content
  .third__stage__header
    .logo-box
      .logo-box__in
        =link_to root_path do
          = image_tag "fmarket_logo_red.svg", size: "185x49", alt: "フリマのアイコン"
  .center
    .center__content
      .center__content__text
        %h2購入内容の確認
      .product__photo__box
        .product__photo__box__inner
          .img
            = image_tag "#{@images.first.src}"
          .description
            .name
              = @product.name
            .name__line
              ¥
              = @product.price
              .tax__shipping（税込）送料込み
      .purchase__form__box
        .box__in
          .payment支払い金額
          .price__tag
            ¥
            = @product.price
        .point
          =check_box_tag :check1
          =label_tag :check1, "ポイントを使用 (所持ポイント: P0)"

        .user__card__payment
          .method支払い方法
          .change
            = link_to "変更する" , mypages_path
        .buy__card
          %h4カードナンバー
          %br
          = "**** **** **** " + @default_card_information.last4
          %br
          有効期限
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          = exp_month + " / " + exp_year
          .card__brand
          = image_tag "visa.png", size: "34x20", alt: "カード"
        .user__address
          配送先
          .shipping        
          .change
            = link_to "変更する" , mypages_path
            
        .postnumber 
        〒
        = @address.postal_code
        .address__first
          = @address.city_ward
        .address__second
          = @address.address  
        .buy__name

        .user__address
      .purchase__box
        = link_to pay_purchase_path, method: :post, class: "purchase__box__btn" do
          購入する
      .text
    .footer
      .footer_center
        プライバシーポリシー Fmarket利用規約 特定商取引
        .gray
          =link_to root_path do
            = image_tag "logo_gray.svg", size: "80x65", alt: "フリマのアイコン"
        .inc © Fmarket, Inc.

app/views/products/purchase_done.html.haml
.purchase-done-content
  .header-content
    = link_to root_path do
      = image_tag "fmarket_logo_red.svg", size: "185x49", alt: "フリマのアイコン"
  .second-content
    %h2 購入が完了しました
  .regist_main
    .center_box
      .done__message
        .back-btn
          =link_to root_path do
            %button.btn{type: "submit"} マイページへ戻る
  .footera
    .footer-centera
      プライバシーポリシー メルカリ利用規約 特定商取引
      .gray
        = link_to root_path do
          = image_tag "logo_gray.svg", size: "80x65", alt: "フリマのアイコン"
      .inc © Mercari, Inc.

app/views/products/show.html.haml
%header.products-toppage-header
  = render 'products/header'
.details-page
  %section.product-box
    %h1.product-name
      = @product.name
    .product-box__main-content
      .product-box__main-content__photo
        .product-box__main-content__photo__main-photo
          = image_tag @images[0].src, class:"photo-main"
          .itembox__image__sold-mark
            - if @product.buyer_id != nil
              = render 'sold'
        .product-box__main-content__photo__sub-photo 
          - @images.each do |i|
            = image_tag i.src, class:"photo-list"
      .table
        %table.product-table
          %tbody
            %tr
              %th 出品者
              %td 
                = link_to root_path, class: "link"  do
                  = @user.nickname
                .icon-box
                  .icon-box__face-icon
                    = icon( "fas", "grin", class: "icon-good")
                    %span 10
                  .icon-box__face-icon-bc
                    = icon( "fas", "meh", class: "icon-normal")
                    %span 8
                  .icon-box__face-icon-bc
                    = icon( "fas", "frown", class: "icon-bad")
                    %span 0
            %tr
              %th カテゴリー
              %td 
                = link_to root_path, class: "link"  do
                  メンズ
                = link_to root_path, class: "link"  do
                  .details-first-category
                    = icon('fas', 'chevron-right', class:'icon')
                    ジャケット/アウター
                = link_to root_path, class: "link"  do
                  .details-second-category
                    = icon('fas', 'chevron-right', class:'icon')
                    Gジャン/デニムジャケット
            %tr
              %th ブランド
              %td
                = link_to root_path, class: "link"  do
                  = @product.brand
            %tr
              %th 商品のサイズ
              %td M
            %tr
              %th 商品の状態
              %td 
                = @product.state
            %tr
              %th 配送料の負担
              %td 
                = @product.delivery_fee
            %tr
              %th 配送の方法
              %td
                = @product.sending_method
            %tr
              %th 配送元地域
              %td
                = link_to root_path, class: "link"  do
                  = @product.sending_area
            %tr
              %th 発送日の目安
              %td
                = @product.sending_day
    .product-box__price-box
      %span.price
        ¥
        = @product.price
      %span.tax (税込)
      %span.fee 送料込み
      - if user_signed_in?
        - if current_user.id != @product.seller_id
          - if @product.buyer_id != nil
            .soldout
              売り切れました
          - else
            = link_to purchase_product_path, class: "purchase-btn" do
              購入画面に進む
      - else
        - if @product.buyer_id != nil
          .soldout
            売り切れました
        - else
          = link_to purchase_product_path, class: "purchase-btn" do
            購入画面に進む
    .product-box__description
      %p.description-text
        = simple_format @product.discription
    .product-box__description-buttom
      .product-box__description-buttom__like-report
        .product-box__description-buttom__like-report__like
          = link_to root_path, class: "link"  do
            = icon('far', 'heart', class:'icon')
            %span いいね!
            %span 1
        .product-box__description-buttom__like-report__report
          = link_to root_path, class: "link"  do
            = icon('fa', 'flag', class:'icon')
            %span 不適切な商品の報告
      .product-box__description-buttom__right-btn
        = link_to root_path, class: "link-btn" do
          = icon('fas', 'lock', class:'icon')
          %span あんしん・あんぜんのへの取組
  - if user_signed_in? && current_user.id == @product.seller_id && @product.buyer_id == nil
    %section.product-box
      .product-box__if
        = link_to "商品の編集", "/products/#{@product.id}/edit", method: :get, class: "ifedit"
      %p or
      .product-box__if
        = link_to "この商品を削除する", product_path(@product), method: :delete, class: "ifdelete"
  .product-message
    .product-message__area
      .product-message__area__content
        %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %text_area.message-area
        = link_to root_path, class: "message-btn" do
          コメントする
  %ul.product-next-link
    %li.nexta
      = link_to root_path, class: "link"  do
        = icon('fas', 'chevron-left', class:'left-icon')
        マジェスティックレゴン／シアードット花柄ブラウス／ネイビー系
    %li.nextb
      = link_to root_path, class: "link"  do
        レミレリーフ  ダウンベスト  カモフラ柄
        = icon('fas', 'chevron-right', class:'right-icon')
  .media-box
    %ul.media
      %li.face-icon
        = link_to "http://www.facebook.com/share.php?u=https%3A%2F%2Fitem.mercari.com%2Fjp%2Fm98961557293%2F", target: "_blank", class: "link" do
          = icon('fab', 'facebook-square', class:'icon-face')
      %li.twitter-icon
        = link_to "https://twitter.com/login?lang=ja", target:"_blank", class:"link" do
          = icon('fab','twitter-square', class: 'icon-twitter')
      %li.pintereset-icon
        = link_to "https://www.pinterest.jp/", target:"_blank", class:"link" do
          = icon('fab','pinterest-square', class: 'icon-pintereset')
  .product-list
    %section.user-product
      %h2 
        = link_to 'ユーザーのその他の商品', "root_path", class: "user-page"
      .image-space
        %section.image-box
          = link_to "root_path", class: "product-link" do
            .photo
              = image_tag "tanbo.jpg", class:"photo-box"
            .photo-text
              %h3.product-name
                ズボン
              .product-bottom
                .product-bottom__yen ¥1,000
                .product-bottom__heart
                  = icon('far', 'heart', class:'icon')
                  %span 1
        %section.image-box
          = link_to "root_path", class: "product-link" do
            .photo
              = image_tag "tanbo.jpg", class:"photo-box"
            .photo-text
              %h3.product-name
                ズボン
              .product-bottom
                .product-bottom__yen ¥1,000
                .product-bottom__heart
                  = icon('far', 'heart', class:'icon')
                  %span 1
        %section.image-box
          = link_to "root_path", class: "product-link" do
            .photo
              = image_tag "tanbo.jpg", class:"photo-box"
            .photo-text
              %h3.product-name
                ズボン
              .product-bottom
                .product-bottom__yen ¥1,000
                .product-bottom__heart
                  = icon('far', 'heart', class:'icon')
                  %span 1
    %section.relation-product
      %h2 
        = link_to '関連するその他の商品', "root_path", class: "user-page"
      .image-space
        %section.image-box
          = link_to "root_path", class: "product-link" do
            .photo
              = image_tag "tanbo.jpg", class:"photo-box"
            .photo-text
              %h3.product-name
                ズボン
              .product-bottom
                .product-bottom__yen ¥1,000
                .product-bottom__heart
                  = icon('far', 'heart', class:'icon')
                  %span 1
        %section.image-box
          = link_to "root_path", class: "product-link" do
            .photo
              = image_tag "tanbo.jpg", class:"photo-box"
            .photo-text
              %h3.product-name
                ズボン
              .product-bottom
                .product-bottom__yen ¥1,000
                .product-bottom__heart
                  = icon('far', 'heart', class:'icon')
                  %span 1
        %section.image-box
          = link_to "root_path", class: "product-link" do
            .photo
              = image_tag "tanbo.jpg", class:"photo-box"
            .photo-text
              %h3.product-name
                ズボン
              .product-bottom
                .product-bottom__yen ¥1,000
                .product-bottom__heart
                  = icon('far', 'heart', class:'icon')
                  %span 1
  %nav.details-show-footer 
    %ul
      %li.user-mypage-header__menu
        = link_to root_path, class: "user-mypage-header__menu__item" do
          メルカリ
        = icon('fas', 'chevron-right', class:'icon')
      %li.user-mypage-header__menu
        %span{:itemprop => "title"} 商品名
  .products-toppage-footer-app
    = render 'footer-app'
  %footer.products-toppage-footer-company
    = render 'footer-company'
    